# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7,7))
X, X.shape, X.dtype

(tensor([[0.3873, 0.6552, 0.8435, 0.7459, 0.7147, 0.7184, 0.4315],
         [0.6903, 0.8867, 0.6671, 0.5936, 0.2278, 0.9074, 0.4404],
         [0.8119, 0.7456, 0.5940, 0.4285, 0.2879, 0.9482, 0.3583],
         [0.8040, 0.0675, 0.5268, 0.7644, 0.1970, 0.1617, 0.1033],
         [0.9632, 0.8921, 0.1433, 0.2388, 0.9425, 0.5086, 0.2181],
         [0.6377, 0.9477, 0.9495, 0.4183, 0.9254, 0.0205, 0.4860],
         [0.8445, 0.6696, 0.5448, 0.2840, 0.7866, 0.4747, 0.6114]]),
 torch.Size([7, 7]),
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
Y = torch.rand(size=(1,7))
# Perform matrix multiplication
Z = torch.matmul(X, Y.T)
Z, Z.shape, Z.dtype

(tensor([[1.8827],
         [1.7952],
         [1.7597],
         [1.3055],
         [1.9522],
         [2.0122],
         [1.9591]]),
 torch.Size([7, 1]),
 torch.float32)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
A = torch.rand(size=(7,7))
B = torch.rand(size=(1,7))
# Matrix multiply tensors
C = torch.matmul(A, B.T)
C, C.shape, C.dtype

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]),
 torch.float32)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [2]:
import torch

In [3]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
L = torch.rand(size=(2,3)).to(device)
K = torch.rand(size=(2,3)).to(device)
L, K

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
C = torch.matmul(L, K.T)
C, C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
print(torch.max(C))
# Find min
print(torch.min(C))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [6]:
# Find arg max
print(torch.argmax(C))

# Find arg min
print(torch.argmin(C))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [7]:
# Set seed
torch.manual_seed(7)

# Create random tensor
J = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
E = J.squeeze()


# Print out tensors and their shapes
J, J.shape, E, E.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))